### ISSUE TITLE
Crashing with module not found

### ISSUE THREAD

**Issue by xoxfaby** [Wingysam/Christmas-Community#126]
I'm running through docker and I am repeatedly getting this:

```
2023-12-21T21:08:42.387418092Z 
2023-12-21T21:08:42.387479201Z > christmas-community@1.35.0 start
2023-12-21T21:08:42.387492680Z > node src/manager.js
2023-12-21T21:08:42.387500132Z 
2023-12-21T21:08:42.476790897Z node:internal/modules/cjs/loader:1147
2023-12-21T21:08:42.476835368Z   throw err;
2023-12-21T21:08:42.476843296Z   ^
2023-12-21T21:08:42.476849936Z 
2023-12-21T21:08:42.476856539Z Error: Cannot find module 'child-process-promise'
2023-12-21T21:08:42.476863317Z Require stack:
2023-12-21T21:08:42.476869749Z - /usr/src/app/src/manager.js
2023-12-21T21:08:42.476876520Z     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2023-12-21T21:08:42.476884563Z     at Module._load (node:internal/modules/cjs/loader:985:27)
2023-12-21T21:08:42.476891243Z     at Module.require (node:internal/modules/cjs/loader:1235:19)
2023-12-21T21:08:42.476897667Z     at require (node:internal/modules/helpers:176:18)
2023-12-21T21:08:42.476904557Z     at Object.<anonymous> (/usr/src/app/src/manager.js:1:18)
2023-12-21T21:08:42.476927594Z     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2023-12-21T21:08:42.476933844Z     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2023-12-21T21:08:42.476940013Z     at Module.load (node:internal/modules/cjs/loader:1207:32)

```

**Comment by Wingysam** [comment]
Is this on x64 or arm?

**Comment by Wingysam** [comment]
![image](https://github.com/Wingysam/Christmas-Community/assets/18403742/600add66-29df-49b0-b40c-89cff62eeb69)
Here's what I see trying to run :1.35.0

**Comment by xoxfaby** [comment]
x64

**Comment by Wingysam** [comment]
I'm also on x64. This is the exact issue Docker is meant to prevent. What do you see if you try `docker image ls wingysam/christmas-community`? Here's what I see:
![image](https://github.com/Wingysam/Christmas-Community/assets/18403742/038d92ba-e121-45c6-8a37-bb2f9b0cc350)

**Comment by xoxfaby** [comment]
```
root@docker:~# docker image ls wingysam/christmas-community
REPOSITORY                     TAG       IMAGE ID       CREATED         SIZE
wingysam/christmas-community   latest    ef9f227bbc88   5 days ago      254MB
wingysam/christmas-community   <none>    cf35dbb1c01f   10 months ago   244MB

```

**Comment by Wingysam** [comment]
Try this:
```
docker images --format '{{.Repository}}:{{.Tag}}' | grep 'wingysam/christmas-community:' | xargs docker rmi -f
```

**Comment by xoxfaby** [comment]
```
root@docker:~# docker images --format '{{.Repository}}:{{.Tag}}' | grep 'wingysam/christmas-community:' | xargs docker rmi -f
Untagged: wingysam/christmas-community:latest
Untagged: wingysam/christmas-community@sha256:34a3ab430d37f4b832e0b5cee37299649a2af77469cd9a736a8feccaa8420ee3
Error response from daemon: invalid reference format

```

**Comment by xoxfaby** [comment]
I deleted the container and ran ` docker image prune -a` and it seems to work now.

**Comment by xoxfaby** [comment]
```
2023-12-21T22:04:50.149771770Z node:internal/modules/cjs/loader:1147
2023-12-21T22:04:50.149841929Z   throw err;
2023-12-21T22:04:50.149850332Z   ^
2023-12-21T22:04:50.149875098Z 
2023-12-21T22:04:50.149881482Z Error: Cannot find module 'session-pouchdb-store'
2023-12-21T22:04:50.149887565Z Require stack:
2023-12-21T22:04:50.149897825Z - /usr/src/app/src/index.js
2023-12-21T22:04:50.149907839Z     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2023-12-21T22:04:50.149933567Z     at Module._load (node:internal/modules/cjs/loader:985:27)
2023-12-21T22:04:50.149939942Z     at Module.require (node:internal/modules/cjs/loader:1235:19)
2023-12-21T22:04:50.149945930Z     at require (node:internal/modules/helpers:176:18)
2023-12-21T22:04:50.149951800Z     at Object.<anonymous> (/usr/src/app/src/index.js:5:22)
2023-12-21T22:04:50.149962060Z     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2023-12-21T22:04:50.149969473Z     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2023-12-21T22:04:50.149980408Z     at Module.load (node:internal/modules/cjs/loader:1207:32)
2023-12-21T22:04:50.149988413Z     at Module._load (node:internal/modules/cjs/loader:1023:12)
2023-12-21T22:04:50.150002545Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
2023-12-21T22:04:50.150009106Z   code: 'MODULE_NOT_FOUND',
2023-12-21T22:04:50.150015105Z   requireStack: [ '/usr/src/app/src/index.js' ]
2023-12-21T22:04:50.150021131Z }
2023-12-21T22:04:50.150033955Z 
2023-12-21T22:04:50.150040034Z Node.js v20.10.0```

etc.

**Comment by Wingysam** [comment]
I'm not really sure what's going on. Have you tried running :latest?

**Comment by xoxfaby** [comment]
same error

**Comment by xoxfaby** [comment]
for extra info this is my compose file, ran via portainer
```
version: "3"
services:
  christmas-community:
    image: wingysam/christmas-community:latest
    volumes:
      - /media/config/christmas-community:/data
    ports:
      - 8080:80
    environment:
      PUID: PUID
      PGID: PUID
      SITE_TITLE: "Title"
      SHORT_TITLE: "Wishlist"
      SMILE: 'true'
      TABLE: 'true'
      SINGLE_LIST: 'true'
      LISTS_PUBLIC: 'true'
      MARKDOWN: 'true'
      TRUST_PROXY: ip
    restart: unless-stopped
```

**Comment by zethis** [comment]
Hey @xoxfaby just for testing purpose, could you please run a new container without any persistant data and see what append please ?
`docker run -p 8081:80 -it  wingysam/christmas-community:latest`

**Comment by xoxfaby** [comment]
> Hey @xoxfaby just for testing purpose, could you please run a new container without any persistant data and see what append please ? `docker run -p 8081:80 -it wingysam/christmas-community:latest`

same error

**Comment by Wingysam** [comment]
Try running it with no env variables?

**Comment by jskiddie** [comment]
@xoxfaby please make shure "/media/config/christmas-community" can be accessed by docker and `TRUST_PROXY` doesn't have the value `ip` but an IP-Address instead.

**Comment by xoxfaby** [comment]
> Try running it with no env variables?

wouldn't @zethis test have done that?

**Comment by jskiddie** [comment]
> > Try running it with no env variables?
> 
> wouldn't @zethis test have done that?

In theory yes. In reality your error already changed twice [from](https://github.com/Wingysam/Christmas-Community/issues/126#issue-2053062253) `Error: Cannot find module 'child-process-promise'` [to](https://github.com/Wingysam/Christmas-Community/issues/126#issuecomment-1866991767) `Error: Cannot find module 'session-pouchdb-store'` which I find very strange already and without any complete logs for any one of the incidents I don't really know what is behind `same error` [here](https://github.com/Wingysam/Christmas-Community/issues/126#issuecomment-1867587983).
So I just made suggestions based on what seemed to be the issue when I was able to reproduce the error and furthermore matched the logs you provided so far.

**Comment by xoxfaby** [comment]
I have been getting both of these the whole time.

**Comment by cj13579** [comment]
@xoxfaby is this still happening or have you long since given up?
